name: build

on:
  push:
    branches: 
      - "master"
      - "issues-431-gh-actions" 
  pull_request:
    branches: 
      - "master"

  # run workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: support ape bins
        run: sudo sh -c "echo ':APE:M::MZqFpD::/bin/sh:' >/proc/sys/fs/binfmt_misc/register"

      - name: make everything
        run: make -j8


